# Generated by Django 5.1.3 on 2024-11-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='BooleanField',
        ),
        migrations.RemoveField(
            model_name='game',
            name='DecimalField',
        ),
    ]
